stages:
  - Test
  - Deploy

Version Check:
  stage: Test
  tags:
    - linux
    - maven.smartechnology.com.br
  script:
    - MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - echo '';
      if [ "$CI_COMMIT_TAG" == "$MAVEN_VERSION" ]; then
        echo '';
        echo "OK - A vers達o das tags do git ($CI_COMMIT_TAG) e do maven ($MAVEN_VERSION) est達o iguais";
        echo '';
        exit 0;
      else
        echo "ERRO - A vers達o das tags do git ($CI_COMMIT_TAG) e do maven ($MAVEN_VERSION) est達o diferentes";
        echo '';
        exit 1;
      fi
  only:
    - tags
  except:
    - branches

Maven Deploy:
  stage: Deploy
  tags:
    - linux
    - maven.smartechnology.com.br
  script:
    - mvn clean install package
    - mvn deploy
  artifacts:
    paths:
      - target/*.jar
      - target/*.war
  only:
    - tags
  except:
    - branches

